
# name: Show infomation

on:
  push:
    branches: [ '*' ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
     - name: Show github context
       run: echo '${{ toJson(github) }}'
     - name: Show github env
       run: echo ${GITHUB_ENV}
     - name: Cat github env
       run: cat ${GITHUB_ENV}
     - name: Show memory
       run: free -h
     - name: Show cpu
       run: lscpu
     - name: Set environment variable
       run: echo "MY_VAR=some_value" >> $GITHUB_ENV
     - name: Use environment variable
       run: echo "MY_VAR is $MY_VAR"
     - name: Set working directory
       run: pwd
     - name: Set working directory
       run: pwd
       working-directory: /usr/
     - name: List files in the directory
       run: pwd
       working-directory: ./bin/
